### ISSUE TITLE
Missing data processing script

### ISSUE THREAD

**Issue by ANugmanova** [nicwulab/HA_Abs#1]
Hello, 

First of all, thank you for the article and for sharing the implementation, it’s very interesting!

Also, I would like to ask about the pipeline. According to your bash scrips, the first step of data preparation should be in the file mBLM/script/merge_raw_data.py. But there is no such script. Could you add it? Or could you clarify what is the result of it?

**Comment by Wangyiquan95** [comment]
Thanks for reporting the issue. I have added mBLM/script/merge_raw_data.py. Please let us know if there are any other issues.

**Comment by ANugmanova** [comment]
Thank you a lot! I also see in the script that it uses dataset OAS_memory_paired.csv. Could you clarify how I can get it?

**Comment by Wangyiquan95** [comment]
Hi, the OAS_memory_paired.csv was downloaded and merged from OAS(https://opig.stats.ox.ac.uk/webapps/oas/oas_paired/). Remember to specify Species=Human and BType=Memory-B-cells. Then, you can follow the download guideline.
